#!/bin/bash
#
#
kes=$(whoami)
echo -e "Sisesta aja vaartus: \c"
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then 
	echo "Tere hoomikust $kes!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere paeva $kes"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere ohtu $kes"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ood $kes "
else
	echo "Vale sisend"
fi
#
