#!/bin/bash
#
#
#
echo -n "Sisesta reisijate arv: "
read reisijad
echo "Bussis on $reisija reisijat... "
echo -n "Sisesta mitu kohta on bussis: "
read kohad
bussid=$(($reisiad / $kohad))
ylejaanud=$(($reisijad % $kohad))
if test $ylejaanud -gt 0
then
bussid=$(($bussid + 1))
fi
echo "kokku on vaja $bussid taisbussi"
#


