#!/bin/bash
#
# tervitusskript
#
echo -n "Tere, " # väljasta ilma reavahetuseta Tere,
echo -n "User" # väljasta ilma reavahetuseta User
echo "!" # väljasta ! ja tee reavahetus
#utfyitf79ufg79tg79t
# skripti lõpp
